### ISSUE TITLE
Things to add

### ISSUE THREAD

**Issue by ghost** [FunkyMuffin/Fallout-4-Batch-File-Maker#2]
| Section | Status |
| --- | --- |
| Ammo | 100% |
| Food (not crops) | 0% |
| Stats | 20% |
| Mob spawn | 100% |
| Weapons | 50% |

ideas:
- player scale
- change FOV
- Weather
- Time scale

**Comment by salvadorc17** [comment]
You want to allow spawn multiple mobs of different type, eg. 3 dogs + 2 rats??

**Comment by ghost** [comment]
It's a suggestion some added,

like:
placeatme [radroach_id] 10
placeatme [deathclaw_id] 3

etc.

whatcha think about it? should it be added or not?

**Comment by salvadorc17** [comment]
Let me test that in game, and later can confirm

**Comment by salvadorc17** [comment]
I have tested it works good, also do you want to use npc actors?

**Comment by ghost** [comment]
what kind of npc? I don't think there's a need for general npc spawning ( at least didn't find any reason for that in skyrim)

**Comment by salvadorc17** [comment]
Yes, maybe if you kill them, you will need them late..

**Comment by ghost** [comment]
updated the list, what do you think?

**Comment by salvadorc17** [comment]
yes, add consumables, also companions if needed
