### ISSUE TITLE
Have a batch file for each section?

### ISSUE THREAD

**Issue by salvadorc17** [FunkyMuffin/Fallout-4-Batch-File-Maker#4]
Will be not better idea have different batch file for different functions, i dont want to spawn mobs and add items at time by example..

**Comment by ghost** [comment]
umm maybe,
but the way the 1.1 is built is that the batch file will have only items/actors that has a value of more than 1.

How about splitting the tabs to actors / items / something else

and inside that have another set of tabs / sections for the type of variables?
this way you can set a save option for each main tab (like actors) separately

**Comment by salvadorc17** [comment]
Dont understand well your idea, the tab is not already spittled?
Or you can allow save each category into different file by default items in items.txt, mobs.txt, etc, without need

**Comment by ghost** [comment]
I mean split it to categories and sub-categories.

and wouldn't making different files be annoying for the user that wants to have various things?

he would have to run few bats instead of one

**Comment by salvadorc17** [comment]
Dont sure about your method, maybe you can do it and upload code, after i can check and test it..

**Comment by ghost** [comment]
made a new branch and uploaded

**Comment by salvadorc17** [comment]
Ok, i have checked it, is not bad, but there are categories for actors?? and what else is misisng ( i count consumables, and misc items)

**Comment by ghost** [comment]
Idk, a general name, maybe adding brahim (cows) and dogs or cats over there, maybe even followers (who doesn't want 10 dogmeats?)

what's left is consumables, maybe some weapons, tweaks for maps / FOV stuff like that maybe and perks which is the most difficult part..

**Comment by salvadorc17** [comment]
Yes followers could be a category, why perks is most difficult??

**Comment by ghost** [comment]
because if you want to do grace with the perk system you'll want to give the user an option to choose which level of the perk he wants and no just max it out

**Comment by salvadorc17** [comment]
Why not to max it out, is not about cheat and have all stuff and all perks at maximum level??
