### ISSUE TITLE
Still using this?

### ISSUE THREAD

**Issue by salvadorc17** [FunkyMuffin/Fallout-4-Batch-File-Maker#5]
Youre still using tihs, i have better idea than a Batch file maker, thanks to guy called Alexander Blade, there is a way to create runtime scripts, that allow execute console commands, is called Four Dragon, check for it.

**Comment by ghost** [comment]
all yours

**Comment by salvadorc17** [comment]
So what now, will continue developtment?

**Comment by ghost** [comment]
not sure, I'm drowning in work so I might drop by from time to time- see how I can improve the code a bit. Still it is all your's

**Comment by salvadorc17** [comment]
I also dont have so much time to complete it, because im doing other stuff, will do slow progress

**Comment by ghost** [comment]
Ok, I'll work on extending the perks class, maybe I'll have time over the weekend to progress as well..

**Comment by salvadorc17** [comment]
I will still use same becuase i dont have so much time for code revision or changes, thanks for your help
